# Generated by Django 5.1 on 2026-09-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
