# Generated by Django 5.1 on 2026-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_parent_is_deleted_staff_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', to='students.subject'),
        ),
    ]
