# Generated by Django 5.1 on 2026-09-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_academicclass_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicclass',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='elective_subjects',
            field=models.ManyToManyField(blank=True, related_name='elected_by_students', to='students.subject'),
        ),
        migrations.CreateModel(
            name='ElectiveGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_groups', to='students.academicclass')),
                ('subjects', models.ManyToManyField(related_name='elective_groups', to='students.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('OPTIONAL', 'Optional')], default='COMPULSORY', max_length=20)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'unique_together': {('academic_class', 'subject')},
            },
        ),
    ]
