# Generated by Django 5.1 on 2026-09-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_academicclass_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', through='students.ClassSubject', to='students.subject'),
        ),
    ]
