# Generated by Django 5.1 on 2026-09-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_temp_password',
            field=models.CharField(blank=True, help_text='Temporary password for first-time login', max_length=128, null=True),
        ),
    ]
